<a href="https://colab.research.google.com/github/pratiyushgiri/AIFoundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [8]:
a = np.array([1,2,3,5,7,12])

In [9]:
a[2] = 10

In [15]:
a

array([ 1,  2, 10,  5,  7, 12])

In [17]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0, 100, 11) #create array with evenly spaced number within a spec

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.random.rand(3)

array([0.53135299, 0.54175468, 0.9018972 ])

In [24]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [25]:
np.random.rand(3)*(100)

array([62.11338328, 52.91420943, 13.45799453])

In [27]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(3,5))

array([[40, 15, 72, 22, 43],
       [82, 75,  7, 34, 49],
       [95, 75, 85, 47, 63]])

In [28]:
a = np.arange(5)

In [29]:
b = (10 + (a * 2))

In [30]:
b

array([10, 12, 14, 16, 18])

In [31]:
a > b

array([False, False, False, False, False])

Summarize


In [32]:
a.max()

4

In [33]:
a.sum()

10